### ISSUE TITLE
SSH logs

### ISSUE THREAD

**Issue by pavlovic11** [thinkst/opencanary#103]
Hi,

I'm wondering if I'm doing something wrong regarding SSH config. 
First, when trying to connect to opencanary fake ssh service, ssh command really just hangs.
Second, on ssh connect attempt, in opencanary log I'm seeing only:
`{
  "dst_host": "10.10.20.106",
  "dst_port": 8022,
  "local_time": "2020-10-08 07:31:58.503817",
  "logdata": {
    "SESSION": "5"
  },
  "logtype": 4000,
  "node_id": "opencanary-1",
  "src_host": "10.10.10.27",
  "src_port": 37712
}
`
Command used to connect: 
`ssh -p 8082 user@10.10.20.106`
Shouldn't there be something like "user" in logdata ?  
Relevant part of the config:
` "ssh.enabled": true,`
` "ssh.port": "8022",`
`"ssh.version": "OpenSSH_7.2p2 Ubuntu-4ubuntu2.10",`
Only thing I've changed is `ssh.version` string. Only to better reflect running environment.

Any help is much appreciated

**Comment by jayjb** [comment]
Hi @pavlovic11,

Thanks for giving Opencanary a try. Im sure we will figure this out quickly. Would you mind providing me with some more information of your setup? Your OS? How you running the Opencanary? What SSH client you using to try connect?

**Comment by pavlovic11** [comment]
Hi, 

Opencanary OS: Ubuntu 16.04.7 LTS
Opencanry is running from virtualenv, followed default installation process at [https://github.com/thinkst/opencanary#installation].
Started with `opencanaryd --start`.
Config at `/etc/opencanaryd/opencanary.conf`
I'm using ssh client on Ubuntu 16.04, same version of OS as Opencanary is running on.

**Comment by HybridAU** [comment]
Hey @pavlovic11 

I think the issue is with the ssh version string you are using. I assume you got that from running `ssh -V` 

The problem is that is the version of the OpenSSH _binary_ you have installed on your system, but not the version of the SSH _protocol_ which is what we need. 

I don't have a Ubuntu box with me at the moment to check, but on my ArchLinux box running `ssh -V` gives me
```
OpenSSH_8.3p1, OpenSSL 1.1.1h  22 Sep 2020
```

but running `telnet localhost 22` gives me 
```
Trying ::1...
Connected to localhost.
Escape character is '^]'.
SSH-2.0-OpenSSH_8.3
^]
telnet> q
Connection closed.
```

and it's that `SSH-2.0-OpenSSH_8.3` that we need. The reason your ssh command just hangs is it's getting an SSH version it doesn't know how to deal with.

I think fixing the version string will fix your second issue where the username is not getting sent by your SSH client / logged by OpenCanary.

**Comment by pavlovic11** [comment]
Hey @HybridAU 

this change was not very smart move from my side. 
After restoring default value everything is working!
Thank you for your time!
