### ISSUE TITLE
README.md Install for Ubuntu Broken/Out of date?

### ISSUE THREAD

**Issue by zavalalabs** [thinkst/opencanary#119]
On vanilla install of  Ubuntu 20.10 `sudo apt-get install python-pip` comes back as "not available, however, python3-pip replaces it."

**Comment by zavalalabs** [comment]
In addition: 
`sudo apt-get install python-virtualenv` returns the following:
`sudo apt-get install python-virtualenv
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package python-virtualenv is not available, but is referred to by another package. 
This may mean that the package is missing, has been obsoleted, or is only available from another `

Rather the OS reports  `sudo apt install python3-virtualenv`

**Comment by jayjb** [comment]
Hi @zavalalabs,

Our instructions do need to be updated since they are quite old (I suspect it is forcing you towards python 3 which you should totally go for). Thanks for reporting this. We need to update these for the current (or atleast semi-recent) Ubuntu. 

You can go ahead and install the python3 packages it suggests and continue with the instructions and install `opencanary` into your python 3 virtual environment.

**Comment by ldwedari** [comment]
I had to run this:
apt-get install python3-dev python3-pip python3-virtualenv python3-venv

and create the environment with:
python3 -m venv env/

the:
opencanaryd --start fails because it needs rdp

But the pip3 install rdp fails as well because a version issue.
Besides it is needed to do a pip3 install wheel.
I'm not an expert in python so I don't know how to fix these issues. Hopefully the developers can sort it out.

**Comment by jayjb** [comment]
Hi @ldwedari,

The installation instructions are old (and are being updated shortly). Thank you for letting me know the steps you took. 

Regarding `RDP`, that is a deprecated module that we are redoing. Thanks for reporting it in though. Ill get these instructions updated ASAP

**Comment by jayjb** [comment]
Hi @ldwedari,

Ive updated the installations. Thanks for the push.
