### ISSUE TITLE
Why use encryption algorithms

### ISSUE THREAD

**Issue by yejinyi** [thinkst/opencanary#135]
Hello, I found a des.py file while reading OpenCanary.I know this is an encryption algorithm of the file, but do not understand the honeypot system in the work, why still use encryption, hope to get help, thank you.

**Comment by cecio** [comment]
Hello.

I'm not a developer of the project, so I don't have a deep knowledge of the code base, but I had a look to what you reported and in the code as well:

the `des.py` module is a python implementation of the DES crypto algo and it is used internally by the VNC module. VNC uses DES for authenticating the connecting clients (in some cases), so that's why OpenCanary needs it.

**Comment by jayjb** [comment]
Hi @yejinyi,

@cecio is correct. We use it in the `vnc.py` file.
