### ISSUE TITLE
Correlator

### ISSUE THREAD

**Issue by manincharge** [thinkst/opencanary#154]
Correlator functionality is somewhat a mystery. I have it running, but I'm not sure what the definition of coalesce is relating to alerts.  Is there a certain time period that is considered ? Is it by ip, by service, by both ?  
I would like to be able to adjust those values. 
Also, I would like to implement a filter at the correlator level to reduce certain noise. Can you point me in the right direction for that?

**Comment by jayjb** [comment]
Hi @manincharge,

OpenCanary Correlator is quite old so it doesn't support all alert types (i've made a note to update it actually so thanks for bringing it up).

With regards to "coalesce", Correlator will aim to create a single incident and add subsequent incidents of the same type in a certain time frame from the same attack IP to a single incident. This means that 30 file opens should result in one alert, but the actual incident will contain the information from all 30 attempts. 

What kind of filter would you like to implement? I suspect the handlers.py would be useful because it is the start of handling different alerts individually (you can also look in incidents.py to custom tailor certain incident types).

**Comment by manincharge** [comment]
Hey @jayjb, Regarding the coalesce, what is the default 'certain time frame' and is that configurable in the correlator.conf file ?
I've added functionality for the correlator to call an Azure function App to extend functionality to a SIEM platform, but wasn't aware that all alert types aren't getting to the correlator.  That's kind of a bummer. 
As far as filters, I want to be able to inspect the alerts thru a middle tier and use some logic on whether to alert or take different action.  For instance, I'm considering adding a process to test the detection and ensure all services are working correctly, but not send an actual alert but maybe take other logging action.

**Comment by jayjb** [comment]
Hi @manincharge,

Ye im really sorry about that. We haven't touched the correlator in a while, but ill see if I can buy some time for it today (atleast to update all event types).

With regards to the 'certain time frame', looking through the code, it seems the `'console.incident_horizon'` setting would be a good one to try. It's default is 60 (seconds) which means it would coalesce any incidents of the same type and from the same IP into one incident (with each attempts details added) but only one alert.

So in terms of which alert types do and do not, Im looking at the difference in the code. In the `opencanary-correlator` code base, there is a constants.py which contains the log type number of each incident; there is a similar file in the `opencanary` code base. I suspect there are about 5 missing (which im going to try rectify now). 

In terms of filtering, you could add the IP of the service doing the testing to the ignored IP list, but then the alert wouldn't make it out to the `opencanary-correlator`. With that in mind, we could add a similar functionality to `opencanary-correlator` which would not alert on ignored IPs.

**Comment by manincharge** [comment]
Does SMB go thru the correlator ? I still haven't gotten opencanary to catch the logs that samba is writing. (its taken several hours just to get smb access to show in the samba log)  (ubuntu 20.04)

**Comment by jayjb** [comment]
Hi @manincharge,

Correlator won't be getting any updates. We have plans to make its functionality into the OpenCanary project instead. 

Regarding your questions about SMB, all services' alerts should make it through. 

Im going to close this issue because we have plans for Correlator that would hopefully sort this.
