### ISSUE TITLE
restart opencanary from crontab

### ISSUE THREAD

**Issue by ElBiasto** [thinkst/opencanary#158]
Hey, I want to restart my opencanary every 30 Minutes with Crontab. For testing I set the script to run every 3 Minutes.
When I execute the script manually it's working fine. When it is not working

This is what my script looks like:
`#!/bin/bash`
`SHELL=/bin/sh`
`. /home/pi/.bashrc`
`source /home/pi/canary-env/bin/activate && cd opencanary && opencanaryd --restart`

After creating the script I added it to crontab -e:
`*/3 * * * * /home/pi/restartOC.sh>>test.log`

When I look at the cron.log file I can see that the script is executed:
`Sep 29 08:33:01 DiskStation CRON[20880]: (pi) CMD (cd /home/pi && sh restartOC.sh>>test.log)`

the test.log file stays empty.

Can someone tell me what I'm doing wrong?

**Comment by jayjb** [comment]
Hi @ElBiasto,

If you have installed Opencanary into your virtualenv at `/home/pi/canary-env` already, then you shouldn't need to `cd opencanary` because `opencanaryd` will be added to the `PATH` (iirc). So lets try remove that because if `cron` is running from a working directory that doesn't have `opencanary` directory in it, it may be failing on that.

So to summarise, I would change the final line to:
`source /home/pi/canary-env/bin/activate && opencanaryd --restart`

Let me know how it goes.

**Comment by ElBiasto** [comment]
Hey,
Thank you for your help. I removed the `cd opencanary` but I still have the same problem.
Executing the script manual is still working fine and when it is executed by cron it seems to fail.

**Comment by ElBiasto** [comment]
Fixed it by calling: `/usr/local/bin/activate && opencanaryd --restart` instead

**Comment by jayjb** [comment]
Thanks for letting me know @ElBiasto 🤘
