### ISSUE TITLE
RDP session

### ISSUE THREAD

**Issue by dustinskeeters** [thinkst/opencanary#184]
I see that there is a previous post about this but I can't find a guide to resolve the issue. I am trying to use OpenCanary for a RDP Honeypot project I am doing. I just need to know how to install the RDP module. I go to start OpenCanary and it states "Can't import RDP. Please ensure you have RDP installed" How do I proceed?

**Comment by HybridAU** [comment]
The short answer is that RDP doesn't really work.

The longer answer is that we used the [rdpy](https://pypi.org/project/rdpy) library to make an RDP honey pot, but that library has not had an update since 2015 and only ever supported Python 2 which was end-of-lifed on 1 January 2020. It might be possible to get an old copy of OpenCanary, run it with Python 2 and install the rdpy library.

I naively thought that replacing RPD should be pretty straight forward, after all we don't need to implement the full protocol, just enough of NLA to accept a client connection and then reject the login regardless of what credentials are provided. But after sinking a lot of time into, it just got more and more complex.

Last time I searched for an RDP library that supports Python 3 I didn't find anything useful, I'm not sure how much has changed since then.
