### ISSUE TITLE
SSH private key record

### ISSUE THREAD

**Issue by bbchylml** [thinkst/opencanary#207]
At present, SSH can record the password login information, but cannot record the private key information of private key login. Is it possible?

**Comment by vin01** [comment]
For username and password based authenticattion, passwords are sent to the server. however when using publickey authentication, private keys never leave the client device. Only a signaturee is sent. So they are never directly exposed to the server (a big security benefit of using key based authentication instead of passwords)

- https://www.ietf.org/rfc/rfc4252.txt

**Comment by bbchylml** [comment]
@vin01 Thanks for your reply

**Comment by jayjb** [comment]
Thanks for the explanation @vin01.
