### ISSUE TITLE
Why was the RDP module removed?

### ISSUE THREAD

**Issue by 1Stronk** [thinkst/opencanary#240]
Hello,

This tool is really neat, but I was wondering why the RDP module was removed? Is it because rdpy leverages outdated python libraries and seems to be abandoned? Or any other specific reason?

:)

**Comment by HybridAU** [comment]
@jayjb can probably give a better answer, but I think that's pretty much it;

rdpy only works with Python 2 which was end-of-lifed on the 1st of January 2020 (over 3 years ago at the time of this writing) and rdpy itself hasn't seen any serious development since 2015 (over 8 years ago).

A couple of years ago I looked for an RDP library that worked with Python 3 and found nothing, then I looked at the effort that would be required to port rdpy to Python 3, but that was a staggering amount of work.

It might be possible to write enough of an RDP implementation to listen on port 3389, capture login attempts and return failed for every request without implementing the full RDP spec. But even that I suspect would be a lot of work.

**Comment by 1Stronk** [comment]
> @jayjb can probably give a better answer, but I think that's pretty much it;
> 
> rdpy only works with Python 2 which was end-of-lifed on the 1st of January 2020 (over 3 years ago at the time of this writing) and rdpy itself hasn't seen any serious development since 2015 (over 8 years ago).
> 
> A couple of years ago I looked for an RDP library that worked with Python 3 and found nothing, then I looked at the effort that would be required to port rdpy to Python 3, but that was a staggering amount of work.
> 
> It might be possible to write enough of an RDP implementation to listen on port 3389, capture login attempts and return failed for every request without implementing the full RDP spec. But even that I suspect would be a lot of work.

If its any help, I found this attempt of converting rdpy to python 3, but I cannot comment on its functionality:
https://github.com/citronneur/rdpy/tree/python3

Thanks for elaborating tho!

**Comment by Survial** [comment]
> > rdpy only works with Python 2 which was end-of-lifed on the 1st of January 2020 (over 3 years ago at the time of this writing) and rdpy itself hasn't seen any serious development since 2015 (over 8 years ago).
> > A couple of years ago I looked for an RDP library that worked with Python 3 and found nothing, then I looked at the effort that would be required to port rdpy to Python 3, but that was a staggering amount of work.
> 
> If its any help, I found this attempt of converting rdpy to python 3, but I cannot comment on its functionality: https://github.com/citronneur/rdpy/tree/python3
> 
> Thanks for elaborating tho!

It's working with python2.7, but not with 3.X+

**Comment by jayjb** [comment]
@1Stronk and @Neleus, I've merged the awesome work @HybridAU did for an RDP module.
