### ISSUE TITLE
Missing quotes to "verify": False ?

### ISSUE THREAD

**Issue by alopezme** [thinkst/opencanary#246]
I think you forgot to add quotes to the False keyword. Shouldn't be "False" ?

Disable SSL verification `json
"verify": False
`

**Comment by HybridAU** [comment]
That's a good point, I don't think it needs to be in quotes, but I think it should be lowercase.

I started looking at the docs, and went down a bit of a rabbit hole because it looks like there are a few pages with the extension `.rst` but they are markdown rather than reStructuredText.  This results in some headings and things like syntax highlighting being broken. 

I'll try to do a PR to address that tomorrow.

**Comment by alopezme** [comment]
Thanks. FYI I connected opencanary to a webhook ([https://pypi.org/project/Webhook-Listener/]) listener succesfully using http. But for security reasons I want to do with https, thats why I noticed that.
I am still waitint for the certificate t be generated to do it ;-)
