### ISSUE TITLE
Is there a way to change the appearance of the server?

### ISSUE THREAD

**Issue by rwilli30** [thinkst/opencanary#39]
I can't find any good tutorials on making smb work in the config. Maybe I am confused about how the config actually works. I can get the synology page on port 80 but I can't find the server in my network places and cannot figure out where an intruder would come cross the files 2016-Tender-summary.pdf and the password.docx listed in the .opencanary.conf file. Am I missing something?

**Comment by thinkst** [comment]
Hey @rwilli30,

Sorry for delay. I will take a look and let you know what I find. But in the meantime, you can usually find the smb share using the same IP as the synology page IP, but trying to connect to the IP using an smb client. 

I will ping you back soon with some answers (hopefully!)

**Comment by thinkst** [comment]
Hey @rwilli30,

Have you seen any errors when starting the opencanary daemon? In terms of the SMB share, the opencanary SMB service monitors a local SMB share so you would need to use the config file to point at the relevant files that you would like opencanaryd to monitor. 

Please let me know if this helps at all (otherwise we can continue to figure getting this working!)

**Comment by thinkst** [comment]
Closing this issue for now.
