### ISSUE TITLE
Failed to add service from class CanarySSH in opencanary.modules.ssh

### ISSUE THREAD

**Issue by Raul1718** [thinkst/opencanary#50]
my system is Ubuntu 16.04.4 LTS.

When i run 'opencanaryd --start',hava an error:Failed to add service from class CanarySSH in opencanary.modules.ssh.There was no error in the previous installation process.

[![QQ_20180919162320.jpg](https://i.postimg.cc/BQN9fc4t/QQ_20180919162320.jpg)](https://postimg.cc/1fgYpFgZ)

**Comment by thinkst** [comment]
Hey @Raul1718,

Thanks for getting in contact. Im sorry you having that issue. I have booted up a Ubuntu 16.04 machine and fiddled around in that area. Could you confirm somethings for me please:

1) in `/var/tmp`, do you have `id_dsa` and `id_dsa.pub`? Since it seem the code isnt finding those and hence trying to generate its own.
Although the generation shouldnt be failing, once we confirm that the keys are/aren't there, we can look at trying to generate them externally to remedy the issue.

**Comment by Raul1718** [comment]
Hey @thinkst
this is my /var/tmp contents： 
[![QQ_20180921175039.jpg](https://i.postimg.cc/j280MLhx/QQ_20180921175039.jpg)](https://postimg.cc/vx6NB8jk)
i hav't see id_dsa and id_dsa.pub.

**Comment by Raul1718** [comment]
hey @thinkst
hava an error: 
[![QQ_20180921185102.jpg](https://i.postimg.cc/MTZvH3dv/QQ_20180921185102.jpg)](https://postimg.cc/0638Hngs)

**Comment by thinkst** [comment]
Hey @Raul1718,

Would you mind confirming that you installed all the requirements and followed these steps:
1. `$ sudo apt-get install python-dev python-pip python-virtualenv `
2. `$ virtualenv env/`
3. `$. env/bin/activate`
4. `$ pip install opencanary`

In your screenshot, it looks like you not executing from a virtual environment. If you have followed these steps, activated the virtual environment and still get this issue, then we will need to figure why a Crypto method is failing.

**Comment by jayjb** [comment]
Hey @Raul1718,

The more recent version of OpenCanary contains some fixes for issues with SSH and generating keys. Please give it a go and let me know if it still doesn't work. Im closing this issue for now. Please reopen it if things dont come right.
