### ISSUE TITLE
Samba logs not being sent through e-mail.

### ISSUE THREAD

**Issue by citnadxela** [thinkst/opencanary#53]
I have a Samba share setup.  Whenever someone accesses it, I could see the activity by looking at it at 'var/log/samba-audit.log'.  This is working, however, I thought it was supposed to send an e-mail alert also?  It's currently not.  However, if they access the fake synology page, by inputting the IP into a browser, I get an e-mail alert.  Been stuck on this for a while & would appreciate some help.  If any files need to be looked at, please let me know & I'll post them.

**Comment by thinkst** [comment]
Hey @citnadxela,

Lets see if we can figure this out. From your description, we know that your email credentials are valid and working so we can rule that out. We also know that Samba is logging correctly to `/var/log/samba-audit.log`. 

So the debug steps forward here would be to remove the email output and change that to a local file rather (check the opencanary.org for the logging to file help). We can then tail that file and check that the OpenCanary Samba file watcher is picking up the logging coming from Samba. If we can confirm this first please? (just make sure the opencanary.conf file setting `smb.auditfile` is pointing at the correct Samba logging file - in this case, `/var/log/samba-audit.log`)

Once you have got that working, we can re-enter the email output details

**Comment by citnadxela** [comment]
Hi @thinkst ,

Thanks for the reply.  I think I might've solved it myself, but would probably want to check wi/ you first.  In the /etc/samba/smb.conf file, originally, the logging was configured like this:

full_audit:prefix = %U|%I|%i|%m|%S|%L|%R|%a|%T|%D

I changed %D to %d:

full_audit:prefix = %U|%I|%i|%m|%S|%L|%R|%a|%T|%d

& for some reason, that fixed it & I'm now receiving e-mail alerts whenever a user accesses the Samba share.  Can you please let me know if this is okay?

**Comment by citnadxela** [comment]
I had multiple questions, so in hopes of getting them answered, I'll just ask them here if you don't mind:

1.  When setting up a canary to act like a Windows system running MSSQL, there would be no actual database living on the canary, correct?  It basically just shows itself as a SQL server & the alerts are limited to the attacker trying to authenticate & connect to it?

2.  Is it possible to make the canary an IIS server?

3.  Lastly, what I've been working on wi/ the Samba share is essentially the Windows File Server?

**Comment by citnadxela** [comment]
Hi @thinkst ,

Any update on this?  I plan on deploying this real soon to our live environment, but wanted to get the questions in my previous comment answered first.  Please let me know.  Appreciate it.

**Comment by thinkst** [comment]
Hey @citnadxela,

Sorry for the delay (I completely missed these!)..

Im glad you got the Samba working. 

In terms of that prefix, if you head over to [here](https://www.samba.org/samba/docs/current/man-html/smb.conf.5.html) and under the heading, "Variable Substitutions", you will see that you will now be seeing the processid rather than the name of the domain/workgroup of the user. Is that what you are seeing in your alerts? 

For the next questions, Ill answer them inline:
> When setting up a canary to act like a Windows system running MSSQL, there would be no actual database living on the canary, correct? It basically just shows itself as a SQL server & the alerts are limited to the attacker trying to authenticate & connect to it?

Thats correct. For most of the services, we do not run the actual service deeper than the authentication phase. 

> Is it possible to make the canary an IIS server?

It is possible to create your own skins. If you look at the `http.py` module, you could write your own IIS server quite easily but mimic'ing those services and creating a `iis7` http skin. Let me know if you seriously considering this; Ill be able to help.

> Lastly, what I've been working on wi/ the Samba share is essentially the Windows File Server?

Correct again. The samba module is designed to monitor any Samba share but the golden egg is to look like a valuable Windows File Share on network (since they are everywhere and always contain personal stuff).

I am sorry for the delay in response. Please let us know how it goes and we are glad you are enjoying using OpenCanary.

**Comment by citnadxela** [comment]
@thinkst thank you for everything.  been really enjoying taking the time to learn & use opencanary.  I am seriously considering making canary an IIS server.  if you can perhaps point me in the right direction on how/where to start, it'd be appreciated.  For right now, I'll just try to look at the http.py module & see if i can get the juices flowing.  what would the skin look like because if i'm not mistaken, there's no authentication when it comes to IIS?

**Comment by thinkst** [comment]
hey @citnadxela,

We are so happy you are enjoying the project (we have lots of fun with it too). 

So there are few pointers I can give you to get you started:

1) in `opencanary/modules/data/http` you will see the folder `skin` which contains the two current opencanary skins. In order to add an IIS server; you will need to find a live version of an IIS Server and copy over the html/javascript/css

2) in `opencanary/modules/http.py`, you will need to create a new subclass of a `Resource` (see the BasicLogin class). You can call this `IISLogin`. And basically you will need to mimic how an actual IIS server reacts to POSTs and GETs. This is usually the most time consuming part/ most fun.

Please let me know if you want any more advice/assistance (or have any more questions)

**Comment by citnadxela** [comment]
Hi @thinkst 

What about RDP & apache?  When I try to RDP into the server using Windows Remote Desktop, it's unable to initiate a conncection.  I have it enabled, along wi/ the port in the config file:
![image](https://user-images.githubusercontent.com/40772046/50922243-deacd380-13fe-11e9-9efe-2d29516df829.png)

**Comment by thinkst** [comment]
Hey @citnadxela,

Please make sure you installed the additional dependencies required for rdp: 
`$ sudo apt-get install -y build-essential libssl-dev libffi-dev python-dev
$ pip install rdpy`

If you definitely have installed these. Would you mind scanning your opencanary and checking that the port is open? 

(I ran into a silly issue where I added the `rdp` config values at the top of the config file but didn't remove the `rdp` values that were lower down in the config so the OpenCanary was using those values)

**Comment by citnadxela** [comment]
Hey @thinkst 

The dependencies were installed.
Enabling ufw was how it was resolved:

`sudo ufw enable`

Thanks again.  I had another question if you don't mind.  Is there a way to make the canary act/look like an old Windows XP machine by any chance?  
Let me know.

**Comment by thinkst** [comment]
Hey @citnadxela,

Oh thats great. Im putting together a FAQ (wiki type document) and ill add this to it for sure. Good find!

With OpenCanary, the way to get here is to simply run the sort of services one is likely to find on an XP Machine (the Windows filesharing, and maybe make use of the custom TCP Server to handle some of XP’s small services).

Our paid for [Canary product](https://canary.tools) bundles up features like this into personalities, allowing you to select XP/Windows10, OSX, etc. (This also change the honeypots MAC address to something appropriate and makes sure that the TCP/IP stack responses match the “fake” base personality)

**Comment by citnadxela** [comment]
Hey @thinkst 

Going back to using OpenCanary wi/ IIS/apache.  So I was able to create my own skin.  Everything looks & works fine.  It's a login page similar to the default Synology one.  The only issue I have & possibly hope you can help me on is that when someone attempts to login, I want it to display something similar to this:

![image](https://user-images.githubusercontent.com/40772046/51350073-126da600-1a5c-11e9-804c-d8957cd6e90e.png)

Not quite sure how to achieve this as I don't see in any of the opencanary files if there's JavaScript logic to produce this.  Any help will greatly be appreciated.  Thanks again for everything.

**Comment by thinkst** [comment]
Hey @citnadxela,

Nicely done on getting your own skin working. 

In terms of getting that message on a failed (every) login attempt. I think the best way would be:
1) use javascript to hook into the response, and display that message from the response from the submit (when trying to click login). 
2) server side, you would need to anticipate the request; and make sure the response contains the message you want displayed or a generic `ACCESS_DENIED` with the correct HTTP code (perhaps `401`).

Please let me know how this goes. I would love a PR too (that way we on the same page and I can help by seeing actual code etc).

**Comment by jayjb** [comment]
Hey @citnadxela,

Im closing this issue for now. Please reopen if you would like to continue this discussion.
