### ISSUE TITLE
Error executing scripts

### ISSUE THREAD

**Issue by gertgeunens** [thinkst/opencanary#55]
Hi

I am setting up OpenCanary for a school assesment. 
But when i want to execute the scripts like logger.py in the opencanary directory, the import commands are not found.

Is there something i need to do first to execute this scripts?

**Comment by thinkst** [comment]
Hey @gertgeunens,

Generally the scripts aren't run separately because they are part of the OpenCanary application. 

If you need to run the scripts separately though, you would need to make sure that you have followed the `pip install` instructions into your virtualenv. 

Then whilst that virtualenv is still activated; you can try running the scripts separately. (although i suspect you may still hit some issues).

Is there a reason for trying to run them separately? 

Let me know and we can definitely try figure a way to get this working for you.

**Comment by gertgeunens** [comment]
Hey @thinkst 

We changed to T-Pot as honeypot.
This issue can be closed
