### ISSUE TITLE
opencanary and rdpy required different version of pyasn1.

### ISSUE THREAD

**Issue by prashantvidja** [thinkst/opencanary#63]
Hello,

I was try to install opencanary in my alpine linux machine.
When i was install opencanary then there is not any problem but when I am going to install rdpy then it required pyasn1<0.5.0,>=0.4.1 after that i have install 0.4.1 version of pyasn1. then I have seen error that,
`opencanary 0.4 has requirement pyasn1==0.1.7, but you'll have pyasn1 0.4.1 which is incompatible.`

So which version I need to keep because both required different version at same time.

Thanks
Prashant vidka

**Comment by thinkst** [comment]
Hey @prashantvidja,

Im sorry that you have hit that issue. I have tried to replicate it and found that if I `pip install opencanary` before running `pip install rdpy`, the dependencies work out fine because `rdpy` doesn't specify the version of `pyasn` required. 

That said, ive also gone ahead and tested opencanary using the latest version of `pyasn1`, and it seems to have passed all initial tests. Would you mind trying either of these solutions and letting me know? 

(in order to specify a higher version for opencanary, you would need to `git clone` the opencanary repo, change the `setup.py` file to reflect the latest `pyasn1==0.4.1` and run `pip install .` from in the opencanary repo.)

**Comment by prashantvidja** [comment]
Ok thanks for your replay.
Now it resolved.
