### ISSUE TITLE
No event in samba-audit.log with samba 4.8.3, XFS and CentOS 7.6

### ISSUE THREAD

**Issue by greg-dobedobedo** [thinkst/opencanary#69]
Hello,

The recommended configuration for smb.conf is to audit the succeed pread operations and record them in /var/log/samba-audit.log via rsyslog.

But in my case, I have no 'pread' operation when I open a .txt or a .docx file from the share. 
However, with "full_audit:success = all", I can see many operations including pread_recv and pread_send. See attachment.

I guess we can choose 'open' or 'pread_recv' operation instead in the smb.conf configuration.

I hope it will help other people experiencing the same issue.

[full_success_operations.txt](https://github.com/thinkst/opencanary/files/3228588/full_success_operations.txt)

**Comment by PimDoos** [comment]
A problem with a some of these operations (ex: open) is that they generate more than 3 columns of audit information after the audit prefix, which the current implementation of [`samba.py`](https://github.com/thinkst/opencanary/blob/master/opencanary/modules/samba.py) cannot handle. (it expects 3, and crashes when a log line doesn't conform this format.) 
Pull #68 mitigates this by dropping lines that don't conform the format. This is, however, not ideal, since it excludes all other audit actions from being monitored by OpenCanary.

We're using actions like `connect` `disconnect` `stat` `pread` and `get_nt_acl` to monitor access to the share, even if no files are read.

**Comment by greg-dobedobedo** [comment]
Ok for open. In my case, I chose "full_audit:success = pread_recv" and this works well:

{"dst_host": "10.91.0.158", "dst_port": 445, "local_time": "2019-05-28 16:28:21.609238", "logdata": {"AUDITACTION": "pread_recv", "DOMAIN": "ACC-SERVER", "FILENAME": "2015-ACC-Salaries-NB92.docx", "LOCALNAME": "acc-server", "REMOTENAME": "gva-d150403", "SHARENAME": "accounting", "SMBARCH": "OSX", "SMBVER": "SMB3_11", "STATUS": "ok", "USER": "gmahe"}, "logtype": 5000, "node_id": "gva-filer1", "src_host": "10.91.1.242", "src_port": "-1"}
