### ISSUE TITLE
Setup with SNMP

### ISSUE THREAD

**Issue by gokul-lucifer** [thinkst/opencanary#93]
Hi **jayjab**

I have tried to setup SNMP services, i have installed scary packages, but i coudnt find how to make use of it please help me out to solve me this.

**Comment by jayjb** [comment]
Hi @gokul-lucifer,

Would you mind checking out [these](https://opencanary.readthedocs.io/en/latest/alerts/email.html) and letting me know if it helps?

**Comment by gokul-lucifer** [comment]
hi JayJB,
thank you for this response, i coudnt able to setup *snmp* in opencanary ,
i have no issue with alert
i have installed scary packages after that i dont know what to do to start
snmp

**Comment by jayjb** [comment]
Hi @gokul-lucifer,

Oh sorry; I completely misread that. My apologies. Check to narrow down where the issue is, would you mind posting your `.conf` for your Opencanary setup. 

Another route is to run your OpenCanary using `opencanaryd --dev` which will run everything in the foreground. It will make it easier to pick up any issues or errors you may be having (you can also read more about configuration over [here](https://opencanary.readthedocs.io/en/latest/starting/configuration.html)

**Comment by gokul-lucifer** [comment]
i need to setup SNMP in opencanary, please tell me the command for snmp (example: ftp localhost)

**Comment by jayjb** [comment]
Hi @gokul-lucifer,

Oh you want to test SNMP. We use a tool called [Hydra](https://github.com/vanhauser-thc/thc-hydra). Once you have that installed (it is quick!), you can run:
`$ hydra -p {passwd} snmp://{ip_address} `
where the above `ip_address` is your OpenCanary's IP address and the password is some string.

**Comment by gokul-lucifer** [comment]
hey its ok, below i have pasted my .conf file please do check jayjb



{
    "device.node_id": "opencanary-1",
    "git.enabled": false,
    "git.port" : 9418,
    "ftp.enabled": true,
    "ftp.port": 21,
    "ftp.banner": "FTP server ready",
    "http.banner": "Apache/2.2.22 (Ubuntu)",
    "http.enabled": false,
    "http.port": 80,
    "http.skin": "nasLogin",
    "http.skin.list": [
        {
            "desc": "Plain HTML Login",
            "name": "basicLogin"
        },
        {
            "desc": "Synology NAS Login",
            "name": "nasLogin"
        }
    ],
    "httpproxy.enabled" : false,
    "httpproxy.port": 8080,
    "httpproxy.skin": "squid",
    "httproxy.skin.list": [
        {
            "desc": "Squid",
            "name": "squid"
        },
        {
            "desc": "Microsoft ISA Server Web Proxy",
            "name": "ms-isa"
        }
    ],
    "logger": {
        "class": "PyLogger",
        "kwargs": {
            "formatters": {
                "plain": {
                    "format": "%(message)s"
                }
            },
            "handlers": {
                "console": {
                    "class": "logging.StreamHandler",
                    "stream": "ext://sys.stdout"
                },
                "file": {
                    "class": "logging.FileHandler",
                    "filename": "/var/tmp/opencanary.log"
                }
            }
        }
    },
    "portscan.enabled": false,
    "portscan.logfile":"/var/log/kern.log",
    "portscan.synrate": 5,
    "portscan.nmaposrate": 5,
    "portscan.lorate": 3,
    "smb.auditfile": "/var/log/samba-audit.log",
    "smb.enabled": false,
    "mysql.enabled": false,
    "mysql.port": 3306,
    "mysql.banner": "5.5.43-0ubuntu0.14.04.1",
    "ssh.enabled": true,
    "ssh.port": 22,
    "ssh.version": "SSH-2.0-OpenSSH_5.1p1 Debian-4",
    "redis.enabled": false,
    "redis.port": 6379,
    "rdp.enabled": false,
    "rdp.port": 3389,
    "sip.enabled": false,
    "sip.port": 5060,
    "snmp.enabled": true,
    "snmp.port": 161,
    "ntp.enabled": false,
    "ntp.port": "123",
    "tftp.enabled": false,
    "tftp.port": 69,
    "tcpbanner.maxnum":10,
    "tcpbanner.enabled": false,
    "tcpbanner_1.enabled": false,
    "tcpbanner_1.port": 8001,
    "tcpbanner_1.datareceivedbanner": "",
    "tcpbanner_1.initbanner": "",
    "tcpbanner_1.alertstring.enabled": false,
    "tcpbanner_1.alertstring": "",
    "tcpbanner_1.keep_alive.enabled": false,
    "tcpbanner_1.keep_alive_secret": "",
    "tcpbanner_1.keep_alive_probes": 11,
    "tcpbanner_1.keep_alive_interval":300,
    "tcpbanner_1.keep_alive_idle": 300,
    "telnet.enabled": false,
    "telnet.port": "23",
    "telnet.banner": "",
    "telnet.honeycreds": [
        {
            "username": "admin",
            "password": "$pbkdf2-sha512$19000$bG1NaY3xvjdGyBlj7N37Xw$dGrmBqqWa1okTCpN3QEmeo9j5DuV2u1EuVFD8Di0GxNiM64To5O/Y66f7UASvnQr8.LCzqTm6awC8Kj/aGKvwA"
        },
        {
            "username": "admin",
            "password": "admin1"
        }
    ],
    "mssql.enabled": false,
    "mssql.version": "2012",
    "mssql.port":1433,
    "vnc.enabled": false,
    "vnc.port":5000
}

**Comment by gokul-lucifer** [comment]
hi jayjb
please tell me the command for set upping snmp that's it jayjb

**Comment by jayjb** [comment]
Hi @gokul-lucifer,

There isnt any special command. Once you have added `snmp.enabled: true` to your config (which you have). It should start up automatically - the same as with the other services (`opencanaryd --start`). If it is not starting up, please ensure you `pip install scapy` since it is a necessary requirement. 

> hi JayJB, thank you for this response, i coudnt able to setup *snmp* in opencanary , i have no issue with alert i have installed scary packages after that i dont know what to do to start snmp

Just to be sure, the package is `scapy`. 

If you have done everything above and it is still not working; please let me know what OS you trying to run it on and whether you are using python 2 or 3. This way i can make sure it is working on my side.

**Comment by gokul-lucifer** [comment]
hi jayjb 
ok i'll check and make my conformation. 
I have another question, i need to add another protocol called profinet 
can be added to opencanary ?? or it much more difficult to add other protocols

**Comment by jayjb** [comment]
If you check in the [here](https://github.com/thinkst/opencanary/tree/master/opencanary/modules) you will see all the different supported protocols and their implementations. You will notice that adding a new protocol would not be too hard because Opencanary provides a framework for running any protocol. 

You would simply need to add a module `profinet.py` and mimic the protocol not fully, but to a degree such that someone who is looking for this protocol is fooled into interacting with it. This will then give you an indication of badness and allow you to send an alert.

We dont have plans currently to add any protocols; but ill raise the issue considering it is a industry standard

**Comment by gokul-lucifer** [comment]
Yeah sounds good, thank you @jayjb it was nice times to use with you. we bring up some changes.....
