### ISSUE TITLE
local_time reported incorrectly

### ISSUE THREAD

**Issue by OzGav** [thinkst/opencanary#96]
Hi all,
When a log entry is made I am finding that the local time is 8 hours out for me. That is I get a report which says `"local_time": "2020-09-09 12:16:42.028417"` but it is actually 2016 where I live. My timezone is GMT+10 and if I type date at the command prompt it shows correctly. I am running opencanary in Ubuntu 18.04 on a trusty Odroid U3.

I can't find anything in the docs about a timezone setting. Any idea what I am missing?

**Comment by jayjb** [comment]
Hi @OzGav,

Thanks for writing in. 

So with regards to local time, we set it using 
`logdata['local_time'] = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S.%f")`
which means we are using utc time. So i would expect a 10 hour difference instead of 8 hours.

We haven't actually got timezone settings added (yet), but that is a good idea (a PR would be great 😁 ).

> That is I get a report which says "local_time": "2020-09-09 12:16:42.028417" but it is actually 2016 where I live.
Im unsure about this. Does your Ubuntu OS think it is 2016? 

Let me know and we can try figure a way forward.

**Comment by OzGav** [comment]
Firstly not sure what happened with the timestamp before but yes it is out by 10 hours so I am getting UTC time.

Since the label in the log is "local_time" is there any reason why the code doesn't just use `datetime.now().strftime("%Y-%m-%d %H:%M:%S.%f")` I could easily do a PR for that if it would be approved? Otherwise I would suggest changing the label to "UTC_time"

**Comment by OzGav** [comment]
Any preference for which of the two options above you want me to do the PR?

**Comment by HybridAU** [comment]
It's @jayjb's call, but my vote would be for changing the label to "UTC_time" 

If you have a large geographically distributed network it just makes life easier to record everything in UTC and convert it only when displaying it.

I know that changing the label would be disruptive for people ingesting the logs into siems, but then having the log times suddenly jump by several hours would be disruptive too. 

Also I think a system is going to break, it's better to fail loudly (can't parse the logs because missing expected field) than subtlety (everything looks ok, but the log times are wrong).

**Comment by jayjb** [comment]
Hi @OzGav,

So as @HybridAU says we can't really change that now and risk breaking systems that are parsing logs etc. We can create a new field though with a correct label. This would not disrupt current systems, but would allow newer systems to use a more accurately labeled field.

**Comment by OzGav** [comment]
OK I have submitted a PR. I am not sure if it meets your requirements. If we keep the `local_time` label as UTC time to avoid breaking anyone's stuff then what do we call the new entry? `real_local_time`?

**Comment by jayjb** [comment]
Hi @OzGav,

Lets chat in the PR. Thanks so much for submitting one.
