### ISSUE TITLE
SSH DSA Key generation error

### ISSUE THREAD

**Issue by kmc56** [thinkst/opencanary#98]
Hi,

There seems to be an error when running the SSH module and generating DSA keys.. this may be down to user error but after seeing a similar issue #50 I thought I'd run it through. Using RHEL 8 with pything 2,7 and pything 3.6 installed.

Error:

{"dst_host": "", "dst_port": -1, "local_time": "2020-09-18 13:21:04.428918", "logdata": {"msg": {"logdata": "Failed to add service from class CanarySSH in opencanary.modules.ssh. Traceback (most recent call last):\n  File \"/etc/env/bin/opencanary.tac\", line 90, in start_mod\n    service = obj.getService()\n  File \"/etc/env/lib/python3.6/site-packages/opencanary/modules/ssh.py\", line 408, in getService\n    dsa_pubKeyString, dsa_privKeyString = getDSAKeys()\n  File \"/etc/env/lib/python3.6/site-packages/opencanary/modules/ssh.py\", line 349, in getDSAKeys\n    serialization.PublicFormat.OpenSSH)\n  File \"/etc/env/lib/python3.6/site-packages/cryptography/hazmat/backends/openssl/dsa.py\", line 256, in public_bytes\n    encoding, format, self, self._evp_pkey, None\n  File \"/etc/env/lib/python3.6/site-packages/cryptography/hazmat/backends/openssl/backend.py\", line 2069, in _public_key_bytes\n    return ssh.serialize_ssh_public_key(key)\n  File \"/etc/env/lib/python3.6/site-packages/cryptography/hazmat/primitives/serialization/ssh.py\", line 680, in serialize_ssh_public_key\n    kformat.encode_public(public_key, f_pub)\n  File \"/etc/env/lib/python3.6/site-packages/cryptography/hazmat/primitives/serialization/ssh.py\", line 313, in encode_public\n    self._validate(public_numbers)\n  File \"/etc/env/lib/python3.6/site-packages/cryptography/hazmat/primitives/serialization/ssh.py\", line 328, in _validate\n    raise ValueError(\"SSH supports only 1024 bit DSA keys\")\nValueError: **SSH supports only 1024 bit DSA keys**\n"}}, "logtype": 1001, "node_id": "QOCHP-1", "src_host": "", "src_port": -1}

**Comment by jayjb** [comment]
Hi @kmc56,

Thanks for reporting this. Ill take a look and get back to you ASAP.

**Comment by HybridAU** [comment]
I remember I ran into that `SSH supports only 1024 bit DSA keys` error when I was doing the PR for [upgrading to cryptography 3.0](https://github.com/thinkst/opencanary/pull/89).

It was due to a change in the [cryptography](https://github.com/pyca/cryptography/blob/3.0/src/cryptography/hazmat/primitives/serialization/ssh.py#L333) library. Importing keys that had already been generated was fine, but generating new keys we needed to [specify 1024 bits](https://github.com/thinkst/opencanary/blob/fea6e084ef718d0ad09d8e3114631b80aa9663d5/opencanary/modules/ssh.py#L345).

Are you installing OpenCanary from source or via pip? it might be worth checking what version of the cryptography library you have installed, if it's 3.0 you need OpenCanary >= 0.5.6

**Comment by kmc56** [comment]
Hi @HybridAU 

Installing using pip installed opencanary 0.5.5. I tried downgrading cryptography but it didn't seem to work.
After installing from source and getting 0.5,6 it worked so thanks for the heads up!
